[package]
name = "tripperjs_wasm"
version = "0.1.0"
edition = "2024"

[lib]
name = "tripperjs_wasm"
path = "src/main.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
rand = "0.8"
getrandom = { version = "0.2", features = ["js"] }